version: 1.2.{build}

build:
  verbosity: detailed

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

artifacts:
  - path: '**\*.msi'
